version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16
  aws-ecr: circleci/aws-ecr@6.3.0
  aws-ecs: circleci/aws-ecs@1.1.0

jobs:
  app_build_and_push_image:
    executor: aws-ecr/default
    steps:
      - checkout
      - run: pwd
      - run: ls -lat
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: "${AWS_ECR_REPO_NAME}"
          region: AWS_DEFAULT_REGION
          tag: "${CIRCLE_SHA1}"
          path: ./Dockerfiles/app/Dockerfile

  batch_build_and_push_image:
    executor: aws-ecr/default
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: "${AWS_ECR_REPO_NAME}"
          region: AWS_DEFAULT_REGION
          tag: "${CIRCLE_SHA1}"
          path: ./Dockerfiles/batch/Dockerfile

  deploy_app:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: >-
          cat deployments/fargate-cluster/task_definition_skelton.json |
            jq '.executionRoleArn |= "'${AWS_ECS_TASK_EXEC_ROLE_ARN}'"' |
            jq '.containerDefinitions[].image |= "'${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO_NAME}:${CIRCLE_SHA1}'"' |
            jq '.containerDefinitions[].logConfiguration.options["awslogs-group"] |= "'/ecs/${AWS_LOG_GROUP_NAME}'"' |
            jq '.containerDefinitions[].logConfiguration.options["awslogs-stream-prefix"] = "'${AWS_LOG_GROUP_NAME}'"' >> ./task_definition.json
      - aws-ecs/update-task-definition-from-json:
          task-definition-json: task_definition.json
      - run:
          command: |
            export TASK_REVISION=`aws ecs list-task-definitions --sort DESC --status ACTIVE --max-items 1 | jq -r ".taskDefinitionArns[0]" | cut -d '/' -f 2`
            aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition ${TASK_REVISION}

workflows:
  version: 2
  deployment:
    jobs:
      - app_build_and_push_image:
          context: deploy-sample-ecs-app
          filters:
            branches:
              only: /master/
      - batch_build_and_push_image:
          context: deploy-sample-ecs-app
          filters:
            branches:
              only: /master/
      - deploy_app:
          context: deploy-sample-ecs-app
          filters:
            branches:
              only: /master/
          requires:
            - app_build_and_push_image