AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Provisioning Template

Resources:
  AppRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: app

  BatchRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: batch
